export const supplierSchemas = {
  CreateSupplierInput: {
    type: 'object',
    required: ['name', 'defaultCurrencyId'],
    properties: {
      name: { type: 'string', minLength: 1, maxLength: 255, example: 'GlobalTech Importer' },
      contactPersonName: { type: 'string', maxLength: 255, nullable: true, example: 'John Doe' },
      email: {
        type: 'string',
        format: 'email',
        maxLength: 255,
        nullable: true,
        example: 'contact@globaltech.com',
      },
      phoneNumber: { type: 'string', maxLength: 50, nullable: true, example: '+1-555-123-4567' },
      website: {
        type: 'string',
        format: 'url',
        maxLength: 2048,
        nullable: true,
        example: 'https://globaltech.com',
      },
      vatNumber: { type: 'string', maxLength: 50, nullable: true, example: 'EU123456789' },
      siretNumber: { type: 'string', maxLength: 50, nullable: true, example: '12345678900010' },
      defaultCurrencyId: { type: 'integer', example: 1, description: 'ID of an existing currency' },
      defaultPaymentTermsDays: { type: 'integer', minimum: 0, nullable: true, example: 30 },
      addressId: {
        type: 'integer',
        nullable: true,
        example: 1,
        description: 'ID of an existing address',
      },
      notes: { type: 'string', nullable: true, example: 'Preferred supplier for electronics.' },
    },
  },
  UpdateSupplierInput: {
    type: 'object',
    properties: {
      name: { type: 'string', minLength: 1, maxLength: 255 },
      contactPersonName: { type: 'string', maxLength: 255, nullable: true },
      email: { type: 'string', format: 'email', maxLength: 255, nullable: true },
      phoneNumber: { type: 'string', maxLength: 50, nullable: true },
      website: { type: 'string', format: 'url', maxLength: 2048, nullable: true },
      vatNumber: { type: 'string', maxLength: 50, nullable: true },
      siretNumber: { type: 'string', maxLength: 50, nullable: true },
      defaultCurrencyId: { type: 'integer' },
      defaultPaymentTermsDays: { type: 'integer', minimum: 0, nullable: true },
      addressId: { type: 'integer', nullable: true },
      notes: { type: 'string', nullable: true },
    },
  },

  EmbeddedAddressDTO: {
    type: 'object',
    properties: {
      id: { type: 'integer' },
      streetLine1: { type: 'string' },
      city: { type: 'string' },
      postalCode: { type: 'string' },
      country: { type: 'string' },
    },
  },
  EmbeddedCurrencyDTO: {
    type: 'object',
    properties: {
      id: { type: 'integer' },
      code: { type: 'string' },
      name: { type: 'string' },
      symbol: { type: 'string' },
    },
  },
  SupplierApiResponse: {
    type: 'object',
    properties: {
      id: { type: 'integer', example: 1 },
      name: { type: 'string', example: 'GlobalTech Importer' },
      contactPersonName: { type: 'string', nullable: true, example: 'John Doe' },
      email: { type: 'string', format: 'email', nullable: true, example: 'contact@globaltech.com' },
      phoneNumber: { type: 'string', nullable: true, example: '+1-555-123-4567' },
      website: { type: 'string', format: 'url', nullable: true, example: 'https://globaltech.com' },
      vatNumber: { type: 'string', nullable: true, example: 'EU123456789' },
      siretNumber: { type: 'string', nullable: true, example: '12345678900010' },
      defaultCurrencyId: { type: 'integer', example: 1 },
      defaultCurrency: { $ref: '#/components/schemas/CreateCurrencyInput', nullable: true },
      defaultPaymentTermsDays: { type: 'integer', nullable: true, example: 30 },
      addressId: { type: 'integer', nullable: true, example: 1 },
      address: { $ref: '#/components/schemas/CreateAddressInput', nullable: true },
      notes: { type: 'string', nullable: true, example: 'Preferred supplier for electronics.' },
      createdByUserId: { type: 'integer', nullable: true },
      updatedByUserId: { type: 'integer', nullable: true },
      createdAt: { type: 'string', format: 'date-time', nullable: true },
      updatedAt: { type: 'string', format: 'date-time', nullable: true },
    },
  },
};
