#!/usr/bin/env sh
# Exécute commitlint pour valider le message de commit
# Nécessite que commitlint soit configuré dans le projet (ex: commitlint.config.js)
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "$1"