#!/bin/sh
# Husky commit-msg hook: validate commit message using commitlint
# Requires commitlint to be configured in the project (e.g., commitlint.config.js)
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "$1"