name: CI/CD Pipeline

on:
  push:
    branches: ['main', 'dev']
  # AJOUTEZ OU ASSUREZ-VOUS QUE CE BLOC EST PRÉSENT
  pull_request:
    branches: ['main', 'dev']
    # types: [opened, reopened, synchronize, ready_for_review] # Vous pouvez affiner les types si besoin
  # Permet le déclenchement manuel du job 'deploy' depuis l'interface GitHub Actions
  workflow_dispatch:

jobs:
  # ==========================================
  # Job: Test
  # ==========================================
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Optionnel: Linting/Formatting
      - name: Lint code
        run: npm run lint
      - name: Check formatting
        run: npm run format

      - name: Ensure test services are stopped
        # Arrête et supprime les conteneurs/volumes précédents via le script npm
        run: npm run test-db:stop
        # Continue même si la commande échoue (par exemple, si les conteneurs n'existaient pas)
        continue-on-error: true

      - name: Start test services
        # Utilise --wait pour attendre que les conteneurs avec healthcheck soient sains (mysql-test, redis-test)
        run: docker compose -f src/tests/docker-compose.yml up -d --wait

      - name: Wait for services to stabilize
        run: sleep 10s

      - name: Run tests
        # npm test utilise 'dotenv -e .env.test', donc les variables ci-dessus seront chargées
        run: npm test

      - name: Stop test services
        if: always()
        run: docker compose -f src/tests/docker-compose.yml down -v

  # ==========================================
  # Job: Build and Push Docker Image
  # ==========================================
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # Ne s'exécute que sur push vers 'main' et après succès du job 'test'
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push'
    needs: test

    # Accorde les permissions nécessaires pour lire le contenu et écrire des packages (images Docker)
    permissions:
      contents: read # Nécessaire pour actions/checkout
      packages: write # Nécessaire pour pusher vers GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # Utilise le token fourni automatiquement par GitHub Actions
          username: ${{ github.actor }} # L'utilisateur qui a déclenché le workflow
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Construit le nom de l'image pour GHCR: ghcr.io/owner/repo
          # Vous pouvez ajouter un nom d'image spécifique si besoin: ghcr.io/${{ github.repository }}/api
          images: ghcr.io/${{ github.repository }} # Ex: ghcr.io/adamsbarry18/innov-stocker.node
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ===========================================
  # Job: Deploy (Manual Trigger)
  # ===========================================
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    # Ne s'exécute que sur déclenchement manuel ('workflow_dispatch')
    # et après succès du job 'build-and-push-docker' (donc implicitement sur 'main')
    if: github.event_name == 'workflow_dispatch'
    needs: build-and-push-docker

    environment: production # Optionnel: Définit un environnement pour les secrets/règles

    steps:
      - name: Checkout repository (si nécessaire pour les scripts de déploiement)
        uses: actions/checkout@v4
        with:
          ref: main # Assurez-vous de déployer depuis main

      - name: Placeholder for Deployment Steps
        run: |
          echo "Deployment triggered manually for branch: ${{ github.ref }}"
          echo "Image to deploy (example): ghcr.io/${{ github.repository }}:latest" # Nom d'image GHCR
          echo "Add your deployment steps here (e.g., SSH, kubectl, serverless deploy, etc.)"
          # Exemple:
          # ssh user@your-server "docker pull your-image:latest && docker stop your-container && docker rm your-container && docker run -d --name your-container your-image:latest"
          # kubectl set image deployment/your-deployment your-container=your-image:latest -n your-namespace
